[Variables]
IconStyle = fading
;static - static color icon
;fading - fading animation from gray to color

HitboxVisible = 1
;0 - transparent Hitbox
;1 - visible Hitbox

SnapGrid = on
;off - Nothing happens on refresh
;on - Icons snap to invisible grid on refresh

;------------------------------------------------

;If you don't want the Wallpaper to be set automatically on "Refresh all", unload "Wallpaper.ini"
