[Variables]
IconStyle = fading
;static - static color icon
;fading - fading animation from gray to color

HitboxVisible = 1
;0 - transparent hitbox
;1 - visible hitbox

SnapGrid = on
;off - Nothing happens on refresh
;on - Icons snap to invisible grid on refresh

;------------------------------------------------

;To apply the settings save the file, go to Rainmeter and hit "Refresh all"

;------------------------------------------------

;If you don't want the Wallpaper to be set automatically on "Refresh all", unload "Wallpaper.ini"
