[Variables]
IconStyle = fading
;static - static color icon
;fading - fading animation from gray to color

HitboxVisible = 1
;0 - transparent hitbox
;1 - visible hitbox

SnapGrid = on
;off - Nothing special happens on refresh
;on - Icons snap to invisible grid on refresh

Hitbox=#HitboxDark#
ActiveColor=255,255,255
InactiveColor=159,159,159
;These are the default colors of the skin. All skins use these values if they don't overwrite them

;------------------------------------------------

;To apply the settings save the file, go to Rainmeter and hit "Refresh all"

;------------------------------------------------

;If you don't want the Wallpaper to be set automatically on "Refresh all", unload "Wallpaper.ini"
