[Variables]
@Include="#@#variables.inc"

[StyleLabelFont]
FontFace=Segoe UI
FontSize=12
StringAlign=Center
AntiAlias=1

[StyleMenuFont]
FontFace=Segoe UI
FontSize=9
FontColor=#MenuFontColor#
AntiAlias=1

[StyleUiDarkFont]
FontFace=Share Tech Mono
StringAlign=CenterCenter
FontColor=#DarkGray#
AntiAlias=1

[StyleUiLightFont]
FontFace=Share Tech Mono
StringAlign=CenterCenter
FontColor=#LightGray#
AntiAlias=1
