[Variables]
IconWith=90
IconHight=104

GridW=45
GridH=78
GridX=8
GridY=0

FadeInStep=20
FadeInRepeat=13
FadeOutStep=4
FadeOutRepeat=64

Hitbox=Hexagon_Dark.png
HitboxDark=Hexagon_Dark.png
HitboxLight=Hexagon_Light.png
HitboxAlpha=1

IconDir=#@#Icons\IconsScaled\

DarkGray=64,64,64,255
MiddleGray=127,127,127,255
LightGray=191,191,191,255

MenuBackgroundColor=43,43,43,255
MenuBorderColor=160,160,160,255
MenuMouseOverColor=65,65,65,255
MenuFontColor=255,255,255,255
